stages:
  - build-frontend
  - build-backend
  - build-image
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  # 前端和后端构建缓存目录
  FRONTEND_CACHE_DIR: ui/node_modules
  GO_CACHE_DIR: ~/.cache/go-build

# 全局缓存配置
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ${FRONTEND_CACHE_DIR}/
    - ${GO_CACHE_DIR}/

build-frontend:
  stage: build-frontend
  image: node:18-alpine
  tags:
    - docker
  cache:
    key: frontend-${CI_COMMIT_REF_SLUG}
    paths:
      - ${FRONTEND_CACHE_DIR}/
  script:
    - cd ui
    - npm install -g pnpm
    - pnpm install
    - pnpm build
  artifacts:
    paths:
      - ui/dist/
    expire_in: 1 hour
  only:
    - main
    - tags

build-backend:
  stage: build-backend
  image: golang:1.20-alpine
  tags:
    - docker
  cache:
    key: backend-${CI_COMMIT_REF_SLUG}
    paths:
      - ${GO_CACHE_DIR}/
  script:
    - apk add --no-cache build-base
    - go mod download
    - go build -o app main.go
  artifacts:
    paths:
      - app
    expire_in: 1 hour
  only:
    - main
    - tags

build-image:
  stage: build-image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - docker
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
      --cache=true
  dependencies:
    - build-frontend
    - build-backend
  only:
    - tags

deploy:
  stage: deploy
  image: alpine:latest
  tags:
    - docker
  variables:
    GIT_STRATEGY: clone
  before_script:
    - apk add --no-cache git openssh-client
    - git config --global user.email "ci@example.com"
    - git config --global user.name "GitLab CI"
  script:
    - sed -i "s#\(image:.*\):.*#\1:$CI_COMMIT_REF_NAME#" $CI_PROJECT_DIR/deploy/k8s.yaml
    - git checkout -B main
    - git add $CI_PROJECT_DIR/deploy/k8s.yaml
    - git commit -m "update image tag to $CI_COMMIT_REF_NAME [skip ci]"
    - git push "https://${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" HEAD:main
  dependencies:
    - build-image
  only:
    - tags
  when: manual
