services:
  redis:
    image: redis:6.2.5
    container_name: redis
    ports:
      - "36379:6379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/redis/data:/data:rw
    command: ["redis-server", "--requirepass", "v6SxhWHyZC7S"]
    restart: always
    networks:
      - cloudOps_net
  asynqmon:
    image: hibiken/asynqmon:latest
    container_name: asynqmon
    ports:
      - "8980:8080"
    command:
      - "--redis-addr=redis:6379"
      - "--redis-password=v6SxhWHyZC7S"
    restart: always
    networks:
      - cloudOps_net
    depends_on:
      - redis

networks:
  cloudOps_net:
    name: cloudOps_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
