global:
    resolve_timeout: 5s
    smtp_require_tls: false
route:
    receiver: admin
    group_by:
        - alert_rule_id,1
        - alert_send_group,1
        - severity,warning
    continue: false
    routes:
        - receiver: test
          matchers:
            - alert_send_group="3"
          continue: false
          repeat_interval: 30s
    group_wait: 5s
    group_interval: 5s
    repeat_interval: 5s
receivers:
    - name: test
      webhook_configs:
        - send_resolved: true
          url: null
          url_file: ./local_yaml/webhook_3_3.txt
          max_alerts: 0
templates: []
