// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	api2 "github.com/GoSimplicity/CloudOps/internal/auth/api"
	"github.com/GoSimplicity/CloudOps/internal/auth/dao/auth"
	"github.com/GoSimplicity/CloudOps/internal/auth/dao/casbin"
	service2 "github.com/GoSimplicity/CloudOps/internal/auth/service"
	api3 "github.com/GoSimplicity/CloudOps/internal/tree/api"
	"github.com/GoSimplicity/CloudOps/internal/tree/dao/ecs"
	"github.com/GoSimplicity/CloudOps/internal/tree/dao/elb"
	"github.com/GoSimplicity/CloudOps/internal/tree/dao/rds"
	"github.com/GoSimplicity/CloudOps/internal/tree/dao/tree_node"
	service3 "github.com/GoSimplicity/CloudOps/internal/tree/service"
	"github.com/GoSimplicity/CloudOps/internal/user/api"
	"github.com/GoSimplicity/CloudOps/internal/user/dao"
	"github.com/GoSimplicity/CloudOps/internal/user/service"
	"github.com/GoSimplicity/CloudOps/pkg/utils/jwt"
	"github.com/gin-gonic/gin"
)

import (
	_ "github.com/google/wire"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := InitRedis()
	handler := jwt.NewJWTHandler(cmdable)
	logger := InitLogger()
	db := InitDB()
	userDAO := dao.NewUserDAO(db, logger)
	enforcer := InitCasbin(db, logger)
	casbinDAO := casbin.NewCasbinDAO(enforcer, logger)
	v := InitMiddlewares(handler, logger, userDAO, casbinDAO)
	userService := service.NewUserService(userDAO)
	userHandler := api.NewUserHandler(userService, logger, handler)
	authDAO := auth.NewAuthDAO(db, logger)
	authService := service2.NewAuthService(authDAO, logger, userDAO)
	authHandler := api2.NewAuthHandler(authService, handler, logger, casbinDAO, userDAO)
	treeEcsDAO := ecs.NewTreeEcsDAO(db, logger)
	treeElbDAO := elb.NewTreeElbDAO(db, logger)
	treeRdsDAO := rds.NewTreeRdsDAO(db, logger)
	treeNodeDAO := tree_node.NewTreeNodeDAO(db, logger)
	treeService := service3.NewTreeService(treeEcsDAO, treeElbDAO, treeRdsDAO, treeNodeDAO, logger, userDAO)
	treeHandler := api3.NewTreeHandler(treeService, logger)
	engine := InitGinServer(v, userHandler, authHandler, treeHandler)
	return engine
}
