// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	api4 "github.com/GoSimplicity/AI-CloudOps/internal/auth/api"
	api2 "github.com/GoSimplicity/AI-CloudOps/internal/auth/dao/api"
	"github.com/GoSimplicity/AI-CloudOps/internal/auth/dao/casbin"
	"github.com/GoSimplicity/AI-CloudOps/internal/auth/dao/menu"
	"github.com/GoSimplicity/AI-CloudOps/internal/auth/dao/role"
	api3 "github.com/GoSimplicity/AI-CloudOps/internal/auth/service/api"
	menu2 "github.com/GoSimplicity/AI-CloudOps/internal/auth/service/menu"
	role2 "github.com/GoSimplicity/AI-CloudOps/internal/auth/service/role"
	api6 "github.com/GoSimplicity/AI-CloudOps/internal/k8s/api"
	"github.com/GoSimplicity/AI-CloudOps/internal/k8s/client"
	dao2 "github.com/GoSimplicity/AI-CloudOps/internal/k8s/dao"
	service3 "github.com/GoSimplicity/AI-CloudOps/internal/k8s/service"
	api7 "github.com/GoSimplicity/AI-CloudOps/internal/prometheus/api"
	dao3 "github.com/GoSimplicity/AI-CloudOps/internal/prometheus/dao"
	service4 "github.com/GoSimplicity/AI-CloudOps/internal/prometheus/service"
	api5 "github.com/GoSimplicity/AI-CloudOps/internal/tree/api"
	"github.com/GoSimplicity/AI-CloudOps/internal/tree/dao/ecs"
	"github.com/GoSimplicity/AI-CloudOps/internal/tree/dao/elb"
	"github.com/GoSimplicity/AI-CloudOps/internal/tree/dao/rds"
	"github.com/GoSimplicity/AI-CloudOps/internal/tree/dao/tree_node"
	service2 "github.com/GoSimplicity/AI-CloudOps/internal/tree/service"
	"github.com/GoSimplicity/AI-CloudOps/internal/user/api"
	"github.com/GoSimplicity/AI-CloudOps/internal/user/dao"
	"github.com/GoSimplicity/AI-CloudOps/internal/user/service"
	"github.com/GoSimplicity/AI-CloudOps/pkg/utils/jwt"
)

import (
	_ "github.com/google/wire"
)

// Injectors from wire.go:

func InitWebServer() *Cmd {
	cmdable := InitRedis()
	handler := jwt.NewJWTHandler(cmdable)
	logger := InitLogger()
	db := InitDB()
	userDAO := dao.NewUserDAO(db, logger)
	enforcer := InitCasbin(db, logger)
	casbinDAO := casbin.NewCasbinDAO(enforcer, logger)
	v := InitMiddlewares(handler, logger, userDAO, casbinDAO)
	userService := service.NewUserService(userDAO)
	userHandler := api.NewUserHandler(userService, logger, handler)
	apiDAO := api2.NewApiDAO(db, logger)
	roleDAO := role.NewRoleDAO(db, logger)
	apiService := api3.NewApiService(apiDAO, roleDAO, logger, userDAO)
	menuDAO := menu.NewMenuDAO(db, logger)
	roleService := role2.NewRoleService(menuDAO, roleDAO, logger)
	menuService := menu2.NewMenuService(menuDAO, logger, userDAO)
	authHandler := api4.NewAuthHandler(apiService, roleService, menuService, handler, logger, casbinDAO, userDAO)
	treeEcsDAO := ecs.NewTreeEcsDAO(db, logger)
	treeElbDAO := elb.NewTreeElbDAO(db, logger)
	treeRdsDAO := rds.NewTreeRdsDAO(db, logger)
	treeNodeDAO := tree_node.NewTreeNodeDAO(db, logger)
	treeService := service2.NewTreeService(treeEcsDAO, treeElbDAO, treeRdsDAO, treeNodeDAO, logger, userDAO)
	treeHandler := api5.NewTreeHandler(treeService, logger)
	k8sDAO := dao2.NewK8sDAO(db, logger)
	k8sClient := client.NewK8sClient(logger, k8sDAO)
	k8sService := service3.NewK8sService(k8sDAO, k8sClient, logger)
	k8sHandler := api6.NewK8sHandler(k8sService, logger)
	prometheusDao := dao3.NewPrometheusDAO(db, logger)
	prometheusService := service4.NewPrometheusService(prometheusDao)
	prometheusHandler := api7.NewPrometheusHandler(prometheusService, logger)
	engine := InitGinServer(v, userHandler, authHandler, treeHandler, k8sHandler, prometheusHandler)
	cron := InitAndRefreshK8sClient(k8sClient, logger)
	cmd := &Cmd{
		Server: engine,
		Cron:   cron,
	}
	return cmd
}
