apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: cicd
  labels:
    name: gitlab
spec:
  selector:
    matchLabels:
      name: gitlab
  template:
    metadata:
      name: gitlab
      labels:
        name: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:18.1.0-ce.0
          imagePullPolicy: IfNotPresent
          env:
            - name: GITLAB_ROOT_PASSWORD
              value: Bamboo@1234
            - name: GITLAB_ROOT_EMAIL
              value: 13664854532@163.com
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: gitlab-config
              mountPath: /etc/gitlab
            - name: gitlab-logs
              mountPath: /var/log/gitlab
            - name: gitlab-data
              mountPath: /var/opt/gitlab
      volumes:
        - name: gitlab-config
          hostPath:
            path: /data/gitlab/conf
        - name: gitlab-logs
          hostPath:
            path: /data/gitlab/logs
        - name: gitlab-data
          hostPath:
            path: /data/gitlab/data
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: cicd
  labels:
    name: gitlab
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30883
  selector:
    name: gitlab
