global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "aiops-platform"
    static_configs:
      - targets: ["aiops-platform:8080"]
    metrics_path: "/api/v1/health/metrics"
    scrape_interval: 30s

  - job_name: "kubernetes-pods"
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true

  - job_name: "kubernetes-nodes"
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - source_labels: [__meta_kubernetes_node_label_kubernetes_io_hostname]
        target_label: instance
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: "kubernetes-cadvisor"
    kubernetes_sd_configs:
      - role: node
    metrics_path: /metrics/cadvisor
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__meta_kubernetes_node_label_kubernetes_io_hostname]
        target_label: instance

  - job_name: "kube-state-metrics"
    static_configs:
      - targets: ["kube-state-metrics:8080"]
    scrape_interval: 30s
    metrics_path: /metrics
