# 服务配置
service:
  name: aiops
  version: 0.1.0
  host: 0.0.0.0
  port: 8000
  debug: true

# 日志配置
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_dir: logs
  max_size: 10485760  # 10MB
  backup_count: 5

# 数据库配置
database:
  time_series:
    type: prometheus
    host: localhost
    port: 9090
  vector:
    type: milvus
    host: localhost
    port: 19530
    collection: aiops_vectors

# 数据收集配置
collectors:
  prometheus:
    host: localhost
    port: 9090
    scrape_interval: 15
  k8s:
    kubeconfig: ~/.kube/config
  logs:
    sources:
      - type: file
        path: /var/log/application/*.log
      - type: kafka
        bootstrap_servers: localhost:9092
        topics: ['app-logs']

# 模型配置
models:
  base_path: models
  default_device: cuda
  cache_dir: .cache/models

# RAG配置
rag:
  embeddings:
    model: sentence-transformers/all-mpnet-base-v2
    dimension: 768
  chunk_size: 1000
  chunk_overlap: 200
  top_k: 5

# API配置
api:
  rate_limit: 100
  timeout: 30
  cors_origins:
    - "*"
  auth:
    enabled: false
    secret_key: "change_this_in_production"

# 智能代理配置
agents:
  healing:
    enabled: true
    interval: 300  # 5分钟
  optimization:
    enabled: true
    interval: 3600  # 1小时
  decision:
    enabled: true
    confidence_threshold: 0.7