# 异常检测模型
anomaly_detection:
  metric:
    model_type: isolation_forest
    contamination: 0.05
    random_state: 42
  log:
    model_type: transformer
    model_name: bert-base-uncased
    max_length: 512
  trace:
    model_type: graph_neural_network
    hidden_channels: 64
    num_layers: 3

# 根因分析模型
root_cause:
  causal_graph:
    model_type: bayesian_network
    structure_learning: pc
  fault_localization:
    model_type: gradient_boosting
    n_estimators: 100
    learning_rate: 0.1

# 预测模型
prediction:
  resource:
    model_type: prophet
    seasonality_mode: multiplicative
    changepoint_prior_scale: 0.05
  failure:
    model_type: lstm
    hidden_size: 64
    num_layers: 2
    dropout: 0.2

# 优化模型
optimization:
  auto_scaling:
    model_type: reinforcement_learning
    algorithm: ppo
    learning_rate: 0.001
  resource_allocation:
    model_type: linear_programming
    solver: cbc