global:
    resolve_timeout: 5m
    smtp_require_tls: false
route:
    group_by:
        - 123,123
        - 4324,23543
    continue: false
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
templates: []
