global:
    resolve_timeout: 5s
    smtp_require_tls: false
route:
    receiver: admin
    group_by:
        - ""
    continue: false
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
templates: []
