// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: aiops/v1/aiops_core.proto

package aiopsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIOpsService_HealthCheck_FullMethodName = "/aiops.v1.AIOpsService/HealthCheck"
	AIOpsService_Chat_FullMethodName        = "/aiops.v1.AIOpsService/Chat"
	AIOpsService_PredictLoad_FullMethodName = "/aiops.v1.AIOpsService/PredictLoad"
)

// AIOpsServiceClient is the client API for AIOpsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI运维服务 - 只包含确实需要的核心功能
type AIOpsServiceClient interface {
	// 健康检查 - 基础功能
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// AI助手对话 - 核心功能，支持流式响应
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error)
	// 负载预测 - 简化版本
	PredictLoad(ctx context.Context, in *LoadPredictionRequest, opts ...grpc.CallOption) (*LoadPredictionResponse, error)
}

type aIOpsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIOpsServiceClient(cc grpc.ClientConnInterface) AIOpsServiceClient {
	return &aIOpsServiceClient{cc}
}

func (c *aIOpsServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AIOpsService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIOpsServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIOpsService_ServiceDesc.Streams[0], AIOpsService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIOpsService_ChatClient = grpc.ServerStreamingClient[ChatResponse]

func (c *aIOpsServiceClient) PredictLoad(ctx context.Context, in *LoadPredictionRequest, opts ...grpc.CallOption) (*LoadPredictionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadPredictionResponse)
	err := c.cc.Invoke(ctx, AIOpsService_PredictLoad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIOpsServiceServer is the server API for AIOpsService service.
// All implementations must embed UnimplementedAIOpsServiceServer
// for forward compatibility.
//
// AI运维服务 - 只包含确实需要的核心功能
type AIOpsServiceServer interface {
	// 健康检查 - 基础功能
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// AI助手对话 - 核心功能，支持流式响应
	Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error
	// 负载预测 - 简化版本
	PredictLoad(context.Context, *LoadPredictionRequest) (*LoadPredictionResponse, error)
	mustEmbedUnimplementedAIOpsServiceServer()
}

// UnimplementedAIOpsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIOpsServiceServer struct{}

func (UnimplementedAIOpsServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAIOpsServiceServer) Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAIOpsServiceServer) PredictLoad(context.Context, *LoadPredictionRequest) (*LoadPredictionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PredictLoad not implemented")
}
func (UnimplementedAIOpsServiceServer) mustEmbedUnimplementedAIOpsServiceServer() {}
func (UnimplementedAIOpsServiceServer) testEmbeddedByValue()                      {}

// UnsafeAIOpsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIOpsServiceServer will
// result in compilation errors.
type UnsafeAIOpsServiceServer interface {
	mustEmbedUnimplementedAIOpsServiceServer()
}

func RegisterAIOpsServiceServer(s grpc.ServiceRegistrar, srv AIOpsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAIOpsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIOpsService_ServiceDesc, srv)
}

func _AIOpsService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIOpsServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIOpsService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIOpsServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIOpsService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIOpsServiceServer).Chat(m, &grpc.GenericServerStream[ChatRequest, ChatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIOpsService_ChatServer = grpc.ServerStreamingServer[ChatResponse]

func _AIOpsService_PredictLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadPredictionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIOpsServiceServer).PredictLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIOpsService_PredictLoad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIOpsServiceServer).PredictLoad(ctx, req.(*LoadPredictionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIOpsService_ServiceDesc is the grpc.ServiceDesc for AIOpsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIOpsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aiops.v1.AIOpsService",
	HandlerType: (*AIOpsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _AIOpsService_HealthCheck_Handler,
		},
		{
			MethodName: "PredictLoad",
			Handler:    _AIOpsService_PredictLoad_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _AIOpsService_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "aiops/v1/aiops_core.proto",
}
