global:
    scrape_interval: 1s
    scrape_timeout: 1s
scrape_configs:
    - job_name: test
      honor_timestamps: false
      track_timestamps_staleness: false
      scrape_interval: 15s
      scrape_timeout: 5s
      metrics_path: /metrics
      scheme: http
      enable_compression: false
      follow_redirects: false
      enable_http2: false
      http_sd_configs:
        - follow_redirects: false
          enable_http2: false
          refresh_interval: 30s
          url: http://localhost:8888/api/not_auth/getTreeNodeBindIps?port=9100&leafNodeIds=
