apiVersion: hpa.aiops.com/v1
kind: PredictHPA
metadata:
  labels:
    app.kubernetes.io/name: hpa-operator
    app.kubernetes.io/managed-by: kustomize
  name: predicthpa-sample
spec:
  deploymentName: "ingress-nginx-controller"
  deployNamespace: "ingress-nginx"
  predictHost: "172.17.99.87:8080"